version: "3.8"
services:
  client:
    build:
      context: ./client
      target: development
    command: npm start
    volumes:
      - ./client:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - webnet

  backend:
    build:
      context: ./server
      target: development
    command: npm run start:dev
    volumes:
      - ./server:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    networks:
      - webnet
      - safenet

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    networks:
      - safenet

networks:
  webnet:
  safenet: