version: "3.9"
services:
  client:
    build: 
      context: ./client
      target: development
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "3000:3000"
    command: ls -l
    networks:
      - webnet
    # depends_on:
    #   - server

  # server:
  #   build: ./server
  #   target: development
  #   command: npm start
  #   volumes:
  #     - .:/usr/src/app
  #     - /usr/src/app/node_modules
  #   ports:
  #     - "3000:3000"
  #   networks:
  #     - network
  #   depends_on:
  #     - server

  # mongo:
  #   image: mongo
  #   ports:
  #     - "27017:27017"

networks:
  webnet: